In [1]:
from pygbif import maps

In [10]:
from pygbif import occurrences as occ
res = occ.search(country='PT', limit=0, facet='speciesKey', )

In [11]:
res

{'offset': 0,
 'limit': 0,
 'endOfRecords': False,
 'count': 25615240,
 'results': [],
 'facets': [{'field': 'SPECIES_KEY',
   'counts': [{'name': '2490719', 'count': 459332},
    {'name': '5231190', 'count': 446464},
    {'name': '2481174', 'count': 360111},
    {'name': '2489104', 'count': 283601},
    {'name': '2492462', 'count': 276507},
    {'name': '2492956', 'count': 271789},
    {'name': '5285565', 'count': 268375},
    {'name': '2495696', 'count': 265571},
    {'name': '9413670', 'count': 259278},
    {'name': '2495414', 'count': 257998}]}]}

In [12]:
import pandas as pd

In [16]:
df = pd.read_csv("/Users/stankutnyk/Downloads/0052673-260226173443078.csv", sep="\t")

In [17]:
df

,taxonKey,scientificName,acceptedTaxonKey,acceptedScientificName,numberOfOccurrences,taxonRank,taxonomicStatus,kingdom,kingdomKey,phylum,...,classKey,order,orderKey,family,familyKey,genus,genusKey,species,speciesKey,iucnRedListCategory
0,2680765,Sematophyllum substrumulosum (Hampe) E.Britton,2680765,Sematophyllum substrumulosum (Hampe) E.Britton,1674,SPECIES,ACCEPTED,Plantae,6,Bryophyta,...,327.0,Hypnales,617.0,Sematophyllaceae,4656.0,Sematophyllum,2680613.0,Sematophyllum substrumulosum,2680765.0,NaN
1,5414457,Centaurium erythraea Rafn,5414457,Centaurium erythraea Rafn,1146,SPECIES,ACCEPTED,Plantae,6,Tracheophyta,...,220.0,Gentianales,412.0,Gentianaceae,2503.0,Centaurium,7412173.0,Centaurium erythraea,5414457.0,LC
2,2680105,Rhynchostegium megapolitanum (Blandow ex F.Web...,2680105,Rhynchostegium megapolitanum (Blandow ex F.Web...,448,SPECIES,ACCEPTED,Plantae,6,Bryophyta,...,327.0,Hypnales,617.0,Brachytheciaceae,4651.0,Rhynchostegium,7441919.0,Rhynchostegium megapolitanum,2680105.0,NaN
3,8417114,Rumex thyrsoides Desf.,8417114,Rumex thyrsoides Desf.,73,SPECIES,ACCEPTED,Plantae,6,Tracheophyta,...,220.0,Caryophyllales,422.0,Polygonaceae,2416.0,Rumex,2888942.0,Rumex thyrsoides,8417114.0,NaN
4,5285165,Pinus pinea L.,5285165,Pinus pinea L.,57351,SPECIES,ACCEPTED,Plantae,6,Tracheophyta,...,194.0,Pinales,640.0,Pinaceae,3925.0,Pinus,2684241.0,Pinus pinea,5285165.0,LC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24573,7069930,Aloe chabaudii var. chabaudii,7069930,Aloe chabaudii var. chabaudii,2,VARIETY,ACCEPTED,Plantae,6,Tracheophyta,...,196.0,Asparagales,1169.0,Asphodelaceae,4259209.0,Aloe,2770879.0,Aloe chabaudii,2777412.0,NaN
24574,3582562,Huernia volkartii var. repens (Lavranos) Lavranos,9327698,Ceropegia volkartii var. repens (Lavranos) Bruyns,1,VARIETY,SYNONYM,Plantae,6,Tracheophyta,...,220.0,Gentianales,412.0,Apocynaceae,6701.0,Ceropegia,7150518.0,Ceropegia volkartii,9439953.0,NaN
24575,7778026,Potamogeton × miguelensis Dandy,5642341,Potamogeton × rivularis Gillot,2,SPECIES,SYNONYM,Plantae,6,Tracheophyta,...,196.0,Alismatales,551.0,Potamogetonaceae,6721.0,Potamogeton,2756560.0,Potamogeton rivularis,5642341.0,NaN
24576,11232951,"Odontopteris Brongniart, 1825",11232951,"Odontopteris Brongniart, 1825",5,GENUS,ACCEPTED,Plantae,6,Tracheophyta,...,NaN,NaN,NaN,Peltaspermaceae,3230416.0,Odontopteris,11232951.0,NaN,NaN,NaN
24577,5428326,"Verrutriletes Pierce, 1961",5428326,"Verrutriletes Pierce, 1961",4,GENUS,PROVISIONALLY_ACCEPTED,Plantae,6,NaN,...,NaN,NaN,NaN,NaN,NaN,Verrutriletes,5428326.0,NaN,NaN,NaN

In [20]:
taxa = pd.read_parquet("./data/taxa.parquet")

In [22]:
df["species"].isin(taxa["species"].unique()).value_counts()

species
True     21811
False     2767
Name: count, dtype: int64

In [24]:
df[['kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species']].to_csv("data/PT_species.csv", index=False,)

In [21]:
taxa

,kingdom,phylum,class,order,family,genus,species,common_name,present_in_taxa,present_in_TOL
0,Plantae,,,,,Alcyonidiopsis,Alcyonidiopsis longobardiae,,False,True
1,Plantae,,,,,Alisporites,Alisporites similis,,False,True
2,Plantae,,,,,Alnipollenites,Alnipollenites verus,,False,True
3,Plantae,,,,,Ampelophyllites,Ampelophyllites Ampelophyllum attenuatum,,False,True
4,Plantae,,,,,Ampelophyllites,Ampelophyllites Populites ovata,,False,True
...,...,...,...,...,...,...,...,...,...,...
393831,Plantae,Tracheophyta,Magnoliopsida,Caryophyllales,Aizoaceae,Aizoanthemopsis,Aizoanthemopsis hispanica,None,None,True
393832,Plantae,Tracheophyta,Magnoliopsida,Ranunculales,Ranunculaceae,Pulsatilla,Pulsatilla vernalis,None,None,True
393833,Plantae,Tracheophyta,Magnoliopsida,Ranunculales,Papaveraceae,Roemeria,Roemeria argemone,None,None,True
393834,Plantae,Tracheophyta,Liliopsida,Asparagales,Orchidaceae,Ophrys,Ophrys sphegodes,None,None,True
393835,Plantae,Tracheophyta,Magnoliopsida,Ranunculales,Ranunculaceae,None,Anemone pratensis,None,None,False