In [5]:
import pandas as pd

from image_to_vector import evaluation_research
from image_to_vector.evaluation_research import (
    load_data, run_similarity_search,
    inference_vanilla, inference_threshold, inference_top_n_softmax,
    evaluate
)

import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
pt_species = pd.read_csv("../data/PT_species.csv")

In [7]:
import json
with open("../data/bioclip2_plantnet300k_metadata.json", "r") as f:
    metadata = json.load(f)

In [8]:
dataset_species = set([el["latin_name"].replace("_", " ") for el in metadata])

In [9]:
len(dataset_species)

1019

In [10]:
(pt_species["species"].drop_duplicates().isin(dataset_species)).value_counts()

species
False    11622
True       396
Name: count, dtype: int64

In [11]:
pd.Series(list(dataset_species)).isin(pt_species["species"]).value_counts()

False    623
True     396
Name: count, dtype: int64

In [12]:
# img_index = "../data/bioclip2_plantnet300k.index"
# img_meta = "../data/bioclip2_plantnet300k_metadata.json"
# text_index = "../data/bioclip2_text_v1.index"
# text_labels = "../data/bioclip2_text_v1_labels.json"
# taxa = "../data/taxa.parquet"
#
# img_vecs_v1_pt, metas_v1_pt, text_idx_v1_pt, labels_v1_pt, taxa_df_v1_pt = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=pt_species["species"].to_list(), )
# scores_v1_pt, indices_v1_pt = run_similarity_search(img_vecs_v1_pt, text_idx_v1_pt, k=5)
#
# img_vecs_v1_pn, metas_v1_pn, text_idx_v1_pn, labels_v1_pn, taxa_df_v1_pn = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=list(dataset_species), )
# scores_v1_pn, indices_v1_pn = run_similarity_search(img_vecs_v1_pn, text_idx_v1_pn, k=5)
#
# img_vecs_v1_all, metas_v1_all, text_idx_v1_all, labels_v1_all, taxa_df_v1_all = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=None, )
# scores_v1_all, indices_v1_all = run_similarity_search(img_vecs_v1_all, text_idx_v1_all, k=5)

# 1. Load Everything
img_index = "../data/bioclip2_plantnet300k.index"
img_meta = "../data/bioclip2_plantnet300k_metadata.json"
text_index = "../data/bioclip2_text_v2.index"
text_labels = "../data/bioclip2_text_v2_labels.json"
taxa = "../data/taxa.parquet"

# img_vecs_v2_pt, metas_v2_pt, text_idx_v2_pt, labels_v2_pt, taxa_df_v2_pt = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=pt_species["species"].to_list(), )
# scores_v2_pt, indices_v2_pt = run_similarity_search(img_vecs_v2_pt, text_idx_v2_pt, k=5)

img_vecs_v2_pn, metas_v2_pn, text_idx_v2_pn, labels_v2_pn, taxa_df_v2_pn = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=list(dataset_species), )
scores_v2_pn, indices_v2_pn = run_similarity_search(img_vecs_v2_pn, text_idx_v2_pn, k=5)

img_vecs_v2_all, metas_v2_all, text_idx_v2_all, labels_v2_all, taxa_df_v2_all = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=None, )
scores_v2_all, indices_v2_all = run_similarity_search(img_vecs_v2_all, text_idx_v2_all, k=5)

Loading Image Index: ../data/bioclip2_plantnet300k.index
Loading Image Metadata: ../data/bioclip2_plantnet300k_metadata.json
Loading Text Index: ../data/bioclip2_text_v2.index
Loading Text Labels: ../data/bioclip2_text_v2_labels.json
Filtering text embeddings...
Filtered text index down to 919 vectors.
Loading Taxonomic Data: ../data/taxa.parquet
Running similarity search for top-5 matches...
Loading Image Index: ../data/bioclip2_plantnet300k.index
Loading Image Metadata: ../data/bioclip2_plantnet300k_metadata.json
Loading Text Index: ../data/bioclip2_text_v2.index
Loading Text Labels: ../data/bioclip2_text_v2_labels.json
Loading Taxonomic Data: ../data/taxa.parquet
Running similarity search for top-5 matches...

KeyboardInterrupt:

In [9]:
preds_v1_all = inference_vanilla(scores_v1_all, indices_v1_all, labels_v1_all, taxa_df_v1_all)
summary, details = evaluate(preds_v1_all, metas_v1_all, taxa_df_v1_all, split_filter=['train', 'val', 'test'])
display(summary)

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
test,31112,0.455066,1.0,0.787987,0.909258,0.920546,0.983223
train,243916,0.458170,1.0,0.791691,0.911150,0.920402,0.983056
val,31118,0.455428,1.0,0.789710,0.909754,0.919266,0.982442

In [10]:
preds_v2_all = inference_vanilla(scores_v2_all, indices_v2_all, labels_v2_all, taxa_df_v2_all)
summary, details = evaluate(preds_v2_all, metas_v2_all, taxa_df_v2_all, split_filter=['train', 'val', 'test'])
display(summary)

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
test,31112,0.603754,1.0,0.861783,0.942882,0.949838,0.991645
train,243916,0.606459,1.0,0.862672,0.944599,0.950358,0.991878
val,31118,0.603895,1.0,0.859838,0.943746,0.949644,0.991852

In [11]:
preds_v1_pt = inference_vanilla(scores_v1_pt, indices_v1_pt, labels_v1_pt, taxa_df_v1_pt)
summary, details = evaluate(preds_v1_pt, metas_v1_pt, taxa_df_v1_pt, split_filter=['train', 'val', 'test'])
display(summary)

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
test,31112,0.523464,1.0,0.776768,0.896266,0.907792,0.977221
train,243916,0.529158,1.0,0.781919,0.898916,0.910007,0.978697
val,31118,0.522816,1.0,0.777824,0.895264,0.907538,0.978180

In [12]:
preds_v2_pt = inference_vanilla(scores_v2_pt, indices_v2_pt, labels_v2_pt, taxa_df_v2_pt)
summary, details = evaluate(preds_v2_pt, metas_v2_pt, taxa_df_v2_pt, split_filter=['train', 'val', 'test'])
display(summary)

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
test,31112,0.614200,1.0,0.832324,0.919488,0.927502,0.982097
train,243916,0.619369,1.0,0.835470,0.921492,0.928546,0.981904
val,31118,0.612154,1.0,0.831489,0.920119,0.928676,0.981726

In [13]:
preds_v1_pn = inference_vanilla(scores_v1_pn, indices_v1_pn, labels_v1_pn, taxa_df_v1_pn)
summary, details = evaluate(preds_v1_pn, metas_v1_pn, taxa_df_v1_pn, split_filter=['train', 'val', 'test'])
display(summary)

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
test,31112,0.647467,1.0,0.922782,0.950793,0.954714,0.986871
train,243916,0.651823,1.0,0.926920,0.953096,0.956524,0.986984
val,31118,0.647921,1.0,0.926331,0.953837,0.957076,0.987181

In [14]:
preds_v2_pn = inference_vanilla(scores_v2_pn, indices_v2_pn, labels_v2_pn, taxa_df_v2_pn)
summary, details = evaluate(preds_v2_pn, metas_v2_pn, taxa_df_v2_pn, split_filter=['train', 'val', 'test'])
display(summary)

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
test,31112,0.743507,1.0,0.954813,0.970503,0.972856,0.994987
train,243916,0.747212,1.0,0.956240,0.971865,0.973886,0.994837
val,31118,0.745421,1.0,0.954656,0.971123,0.973168,0.994477

In [92]:
import evaluation_research
import importlib
importlib.reload(evaluation_research)
from evaluation_research import load_data, run_similarity_search, inference_vanilla, evaluate

In [93]:
img_vecs_v2_all, metas_v2_all, text_idx_v2_all, labels_v2_all, taxa_df_v2_all = load_data(img_index, img_meta, text_index, text_labels, taxa, filter_by_classes=None, split_filter=["train"])

Loading Image Index: ../data/bioclip2_plantnet300k.index
Loading Image Metadata: ../data/bioclip2_plantnet300k_metadata.json
Loading Text Index: ../data/bioclip2_text_v2.index
Loading Text Labels: ../data/bioclip2_text_v2_labels.json
Loading Taxonomic Data: ../data/taxa.parquet

In [94]:
img_vecs_v2_all.shape

(243916, 768)

In [95]:
scores_v2_all, indices_v2_all = run_similarity_search(img_vecs_v2_all, text_idx_v2_all, k=4)

Running similarity search for top-4 matches...

In [ ]:
preds_v2_all = inference_vanilla(scores_v2_all, indices_v2_all, labels_v2_all, taxa_df_v2_all)
summary, details = evaluate(preds_v2_all, metas_v2_all, taxa_df_v2_all, split_filter=['train',])
display(summary)

In [119]:
details["similarity_score"] = scores_v2_all[:, 0]

In [120]:
details["sim_score_decile"] = pd.qcut(details["similarity_score"], q=10, labels=list(range(1,11)))

In [121]:
_, bins = pd.qcut(details["similarity_score"], q=10, labels=list(range(1,11)), retbins=True)

In [122]:
bins_df = pd.DataFrame({"sim_from": bins[:-1], "sim_to": bins[1:]})

In [123]:
pd.merge(details.groupby("sim_score_decile")[["species_match", "genus_match"]].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)

/var/folders/9d/h8rbsks17_q094cwz_ynql6c0000gn/T/ipykernel_1889/1776280538.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pd.merge(details.groupby("sim_score_decile")[["species_match", "genus_match"]].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)

  sim_score_decile  species_match genus_match  sim_from    sim_to
0                1       0.683585    0.810829  0.602381  0.719673
1                2       0.783495     0.89841  0.719673  0.724477
2                3       0.713624    0.869863  0.724477  0.728922
3                4       0.676861     0.87177  0.728922  0.732691
4                5       0.616473    0.864899  0.732691  0.736540
5                6       0.596286    0.866831  0.736540  0.740700
6                7       0.578861    0.868596  0.740700  0.745272
7                8       0.545138     0.87274  0.745272  0.750731
8                9       0.461441    0.854311  0.750731  0.758936
9               10       0.408823     0.84634  0.758936  0.838055

In [124]:
details["top-1-diff"] = scores_v2_all[:, 0] - scores_v2_all[:, 1]

In [125]:
details["diff_decile"], bins = pd.qcut(details["top-1-diff"], q=10, labels=list(range(1,11)), retbins=True)

In [126]:
bins_df = pd.DataFrame({"diff_from": bins[:-1], "diff_to": bins[1:]})

In [127]:
pd.merge(details.groupby("diff_decile")[["species_match", "genus_match", "family_match"]].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)

/var/folders/9d/h8rbsks17_q094cwz_ynql6c0000gn/T/ipykernel_1889/2222287663.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pd.merge(details.groupby("diff_decile")[["species_match", "genus_match", "family_match"]].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)

  diff_decile  species_match genus_match family_match  diff_from   diff_to
0           1       0.205354    0.679228     0.856023   0.000000  0.002357
1           2       0.275869    0.715968     0.875844   0.002357  0.005290
2           3       0.364110     0.75694     0.899692   0.005290  0.008851
3           4       0.486430    0.817194     0.928297   0.008851  0.013171
4           5       0.610676    0.876173     0.955013   0.013171  0.018042
5           6       0.716476    0.913428      0.96943   0.018042  0.023506
6           7       0.784953    0.936418     0.979614   0.023506  0.029807
7           8       0.835274    0.955199     0.986768   0.029807  0.037056
8           9       0.878111    0.965959     0.992087   0.037056  0.045977
9          10       0.907347    0.976541     0.993179   0.045977  0.089434

In [129]:
pd.merge(details.groupby("diff_decile")[["species_match", "genus_match", "family_match"]].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True).to_csv("../data/top_1_diff_decile.csv", index=False)

/var/folders/9d/h8rbsks17_q094cwz_ynql6c0000gn/T/ipykernel_1889/1483476072.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pd.merge(details.groupby("diff_decile")[["species_match", "genus_match", "family_match"]].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True).to_csv("../data/top_1_diff_decile.csv", index=False)

In [33]:
from evaluation_research import inference_margin_threshold

In [107]:
preds_v2_all = inference_margin_threshold(scores_v2_all, indices_v2_all, labels_v2_all, taxa_df_v2_all, margin_threshold=0.013171)

In [108]:
summary, details = evaluate(preds_v2_all, metas_v2_all, taxa_df_v2_all, split_filter=['train', 'val', 'test'])

In [109]:
summary

,Count,Species Accuracy,Species Coverage,Genus Accuracy,Family Accuracy,Order Accuracy,Class Accuracy
Split,,,,,,,
train,243916,0.788819,0.599977,0.862672,0.944599,0.950358,0.991878

In [130]:
indices_correct = indices_v2_all.copy()
for i in range(indices_v2_all.shape[0]):
    correct_class = metas_v2_all[i]["latin_name"].replace("_", " ")
    for j in range(indices_v2_all.shape[1]):
        if labels_v2_all[indices_v2_all[i, j]] == correct_class:
            indices_correct[i, j] = True
        else:
            indices_correct[i, j] = False

In [131]:
indices_correct.sum(axis=0).sum()

np.int64(179447)

In [132]:
indices_correct.sum(axis=0)

array([147925,  18873,   7671,   4978])

In [133]:
sm = softmax(scores_v2_all, axis=1)

In [134]:
sm[:, :3]

array([[0.2590039 , 0.24795328, 0.24668698],
       [0.25291365, 0.25230953, 0.24902892],
       [0.25679946, 0.24810031, 0.24755065],
       ...,
       [0.2543516 , 0.2486289 , 0.24855717],
       [0.2506008 , 0.2500924 , 0.25006983],
       [0.25532305, 0.24894525, 0.24826103]],
      shape=(243916, 3), dtype=float32)

In [135]:
mask_top_1 = indices_correct[:, 0].astype(bool)
mask_top_2 = (indices_correct[:, 1] | mask_top_1).astype(bool)
mask_top_3 = (indices_correct[:, 2] | mask_top_2).astype(bool)

In [136]:
sum(mask_top_1), sum(mask_top_2), sum(mask_top_3)

(np.int64(147925), np.int64(166798), np.int64(174469))

In [137]:
abs_diff_1 = scores_v2_all[:, 0] - scores_v2_all[:, 1]
abs_diff_2 = scores_v2_all[:, 1] - scores_v2_all[:, 2]
abs_diff_3 = scores_v2_all[:, 2] - scores_v2_all[:, 3]

In [138]:
sm_diff_1 = sm[:, :1].sum(axis=1)
sm_diff_2 = sm[:, :2].sum(axis=1)
sm_diff_3 = sm[:, :3].sum(axis=1)

In [142]:
sm_diff1_dec, bins = pd.qcut(abs_diff_1, q=10, labels=list(range(1,11)), retbins=True)
bins_df = pd.DataFrame({"sm_diff1_from": bins[:-1], "sm_diff1_to": bins[1:]})
res = pd.DataFrame({"sm_diff_1": abs_diff_1, "sm_diff1_dec": sm_diff1_dec, "top1": mask_top_1})
res = pd.merge(res.groupby("sm_diff1_dec")["top1"].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)
res["top1_cumsum"] = res.sort_values("sm_diff1_from", ascending=False)["top1"].cumsum()
res["acc_cumcum"] = res["top1_cumsum"] / res["sm_diff1_dec"].sort_values(ascending=False).reset_index(drop=True).astype(float)

/var/folders/9d/h8rbsks17_q094cwz_ynql6c0000gn/T/ipykernel_1889/3409288980.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  res = pd.merge(res.groupby("sm_diff1_dec")["top1"].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)

In [63]:
res

  sm_diff1_dec      top1  sm_diff1_from  sm_diff1_to  top1_cumsum  acc_cumcum
0            1  0.205422       0.000000     0.002350     6.059253    0.605925
1            2  0.275314       0.002350     0.005275     5.853831    0.650426
2            3  0.364343       0.005275     0.008807     5.578517    0.697315
3            4  0.484860       0.008807     0.013115     5.214174    0.744882
4            5  0.607585       0.013115     0.017979     4.729314    0.788219
5            6  0.718056       0.017979     0.023456     4.121729    0.824346
6            7  0.784536       0.023456     0.029763     3.403673    0.850918
7            8  0.833350       0.029763     0.037039     2.619137    0.873046
8            9  0.877932       0.037039     0.045937     1.785787    0.892894
9           10  0.907856       0.045937     0.089434     0.907856    0.907856

In [146]:
sm_diff1_dec, bins = pd.qcut(abs_diff_3, q=10, labels=list(range(1,11)), retbins=True)
bins_df = pd.DataFrame({"diff_from": bins[:-1], "diff_to": bins[1:]})
res = pd.DataFrame({"sm_diff_1": abs_diff_3, "diff_decile": sm_diff1_dec, "species_match_top-3": mask_top_3})
res = pd.merge(res.groupby("diff_decile")["species_match_top-3"].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)
res["top1_cumsum"] = res.sort_values("diff_from", ascending=False)["species_match_top-3"].cumsum()
res["acc_cumcum"] = res["top1_cumsum"] / res["diff_decile"].sort_values(ascending=False).reset_index(drop=True).astype(float)

res

/var/folders/9d/h8rbsks17_q094cwz_ynql6c0000gn/T/ipykernel_1889/3428355391.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  res = pd.merge(res.groupby("diff_decile")["species_match_top-3"].mean().reset_index(), bins_df, how="inner", left_index=True, right_index=True)

,diff_decile,species_match_top-3,diff_from,diff_to,top1_cumsum,acc_cumcum
0,1,0.664371,5.960464e-08,0.000441,7.152834,0.715283
1,2,0.676820,4.405379e-04,0.000932,6.488463,0.720940
2,3,0.686347,9.316802e-04,0.001489,5.811643,0.726455
3,4,0.699697,1.488715e-03,0.002136,5.125296,0.732185
4,5,0.705805,2.135754e-03,0.002907,4.425599,0.737600
5,6,0.723833,2.906919e-03,0.003844,3.719794,0.743959
6,7,0.730843,3.844500e-03,0.005050,2.995961,0.748990
7,8,0.749754,5.049884e-03,0.006781,2.265118,0.755039
8,9,0.759460,6.781220e-03,0.009751,1.515364,0.757682
9,10,0.755904,9.750754e-03,0.056445,0.755904,0.755904

In [148]:
res[["diff_decile", "species_match_top-3", "diff_from", "diff_to",]].to_csv("../data/top_3_diff_decile.csv", index=False)